export const POLYGON_CHAIN_ID = 137;
export const USDC_ADDRESS = '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359'; // Native USDC on Polygon
// TokenMessengerV2 (native) on Polygon mainnet – placeholder, confirm via Circle docs
export const TOKEN_MESSENGER_V2 = '0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d';
// Circle Token Paymaster on Polygon (update when available)
export const CIRCLE_PAYMASTER = '0x0578cFB241215b77442a541325d6A4E6dFE700Ec';
export const SEI_MESSAGE_TRANSMITTER = '0x81D40F21F12A8F0E3252Bccb954D722d4c464B64'; // MessageTransmitterV2 on Sei pacific-1 (update if needed)

export const TERMS_TEXT = `Terms Of Use
Effective Date: June 9, 2025

Aster Foundation and its affiliates and subsidiaries (collectively, "Foundation", "we", "us", "our"), operates this website and any other related website, app, or services that link to these Terms of Use ("Terms"). These Terms govern your access to and use of the Foundation's services, including the app.sei.io website (the "Site"), as well as any other application, media form, media channel, or mobile website related, linked, or otherwise connected thereto that link to these Terms (collectively, the "Services"). Please note that our Privacy Policy describes how we collect, use, and share personal information through the Services and forms a part of these Terms.

The Foundation maintains and operates the Services as a portal for access to, and to provide news, information, analytics, and updates about, the Sei Network protocol or blockchain (collectively, the "Sei Network"), and the Sei Network ecosystem, and in certain instances for interacting with us or with the Sei Network. The Site also offers one or more interfaces to facilitate user interaction with Sei Network services, including functions facilitating wallet connectivity, balance viewing, transaction signing, and token staking or delegation (collectively, the "Sei Interface"). The Site also offers self-custodial wallet creation and management ("Wallet Services"). The Sei Interface and the Wallet Services are integral parts of the Services governed by these Terms.

For avoidance of doubt, the Sei Network is an open-source protocol maintained and processed by Sei Network validators across the globe. The Foundation does not control the Sei Network and cannot control any activity or data on the Sei Network, the activities of persons who develop and use applications on Sei Network, the validation of transactions on the Sei Network, or use of the Sei Network. The Foundation does not control the emission, allocation or transmission of the SEI token.

NOTHING ON OR IN THE SERVICES SHALL CONSTITUTE OR BE CONSTRUED AS AN OFFERING OF ANY CURRENCY, SECURITY OR FINANCIAL INSTRUMENT OR AS INVESTMENT ADVICE.

By accessing or using the Services, you agree that you have reached the age of majority in your jurisdiction and agree to be bound by these Terms. Please read these Terms carefully, as they contain an agreement to arbitrate claims you may have against us and an agreement that you will pursue any claims against us on an individual basis, and not as a plaintiff or class member in any class or representative action or proceeding. By using the Services, you expressly waive any right to participate in a class action lawsuit or class-wide arbitration. If you do not agree to these Terms (including the Privacy Policy linked above), you may not use the Services.

Using Our Services
Eligibility. You may not use the Services if you are below the age of majority in your jurisdiction or it is otherwise illegal in your jurisdiction for you to access, view and/or use the Services. If any of these conditions apply to you, please leave this site immediately. If you do not leave this site, then you will be deemed to have represented that none of these conditions apply to you.

Updates to Terms of Use. Your use of the Services is subject to your agreement to these Terms, which may be updated by us at any time with or without notice to you. The Effective Date of the most up-to-date Terms will be provided at the top of the page for each version of these Terms. Any such updates will be effective upon our publishing such updated Terms. If you do not agree to these Terms, you may not use the Services.

Updates to the Services. We may update and change our Services from time to time at our sole discretion, for example, to reflect changes to our products, our users' needs and our business priorities. We will try to give you reasonable notice of any major changes, but you agree that we will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Service or any costs, expenses, or inconvenience arising out of or related to such modification, suspension, or discontinuance.

No Professional Advice or Fiduciary Duty. All information provided by the Services is for informational purposes only and should not be construed as professional, financial, investment, legal, tax or any other form of advice. Nothing in the Services constitutes an invitation to purchase any digital assets or financial instruments. You should not take, or refrain from taking, any action based on any information contained in the Services. Before you make any financial, legal, or other decisions involving the Services, you should seek independent professional advice from an individual who is licensed and qualified in the area for which such advice would be appropriate.

These Terms are not intended to, and do not, create or impose any fiduciary duties on us. To the fullest extent permitted by law, you acknowledge and agree that we owe no fiduciary duties or liabilities to you or any other party, and that to the extent any such duties or liabilities may exist at law or in equity, those duties and liabilities are hereby irrevocably disclaimed, waived, and eliminated. You further agree that the only duties and obligations that we owe you are those set out expressly in these Terms.

User Conduct
Prohibited Uses. You may not use the Services to engage in the following categories of activity ("Prohibited Uses"). The Prohibited Uses listed below are representative, but not exhaustive, and the Foundation reserves the right to update or amend such list in its sole discretion at any time, with or without notice to you. If you are uncertain as to whether or not your use of the Services involves a Prohibited Use or have questions about how these requirements apply to you, please contact us at foundation@seifdn.org. However, any response or lack of response from us shall not be construed as approval of any particular use or activity. If you make use of our Services, you agree that you will not undertake any of the following, as determined by the Foundation in its sole discretion:

Abusive Activity: Actions which: (i) conduct, facilitate, authorize, or permit any text or data mining or web scraping, (ii) impose an unreasonable or disproportionately large load on our infrastructure, or detrimentally interfere with, intercept, or expropriate any system, data, or information; (iii) transmit or upload any material to the Services that contains viruses, Trojan horses, worms, or any other harmful or deleterious programs; (iv) attempt to gain unauthorized access to the Services, other users' accounts or wallets not belonging to you, computer systems or networks connected to the Services, through password mining or any other means; (v) use the email and password combination of any third party to access or use the Services, except in the case of applications which are specifically authorized by a third party to access or use the Services on such third party's behalf; or (vi) transfer your account access or rights to your account to a third party, unless by operation of law or with the express permission of the Foundation.
Abuse of Other Users: Interference with another person's access to or use of the Services; impersonation of any person or entity or misrepresentation of your affiliation with any person or entity; solicitation of personal information from any person under the age of 18; actions that defame, abuse, extort, harass, stalk, threaten, harm, or otherwise violate or infringe the legal or other rights (such as, but not limited to, rights of privacy, publicity, and intellectual property) of others; or the harvesting or other collection of information from the Services about others, including, without limitation, email addresses or financial information, without proper consent.
Fraud: Activity which operates to defraud the Foundation, any of our user(s) or any other person, or to provide any false, inaccurate, or misleading information to us or others.
Legal Violations: You represent that your access and use of the Services will fully comply with all applicable laws and regulations and that you will not access or use the Services to conduct, promote, or otherwise facilitate illegal activity. You will comply with all applicable sanctions laws, regulations and rules, including but not limited to those administered by the U.S. Department of the Treasury's Office of Foreign Assets Control ("OFAC"), the UK Office of Financial Sanctions Implementation, the European Union, the United Nations, and any other applicable jurisdictions (collectively, the "Sanctions Rules"). You represent and warrant that you are not subject to sanctions or otherwise designated on any list of prohibited or restricted parties under the Sanctions Rules. You may not use the Services access the Site in the jurisdictions prohibited by applicable law.
The Services also may not be used by or for the specific benefit of (i) any individual or entity on the Specially Designated Nationals and Blocked Persons ("SDN") List maintained by OFAC; (ii) any entity 50% or more owned in the aggregate by any such SDN(s); or (iii) for any other use requiring a license or other governmental approval. If Aster Foundation determines, in its sole discretion, that you have breached or may breach your obligations under this section, or that your use of the Services has resulted in or may result in a violation of Sanctions Rules or may subject us to any negative consequences, we reserve the right to immediately block your access to the Services without prior notice.

Access Credentials: You are responsible for maintaining the confidentiality of any credentials used to access the Services and are fully responsible for any and all activities that occur under your credentials. If you learn or suspect that your credentials have been used without your authorization or otherwise compromised, you agree to notify us at the contact information provided below within twenty-four (24) hours of discovering such unauthorized use or compromise.

No Unauthorized Access: If we block you from accessing the Services (including by blocking your IP address), you agree not to circumvent or attempt to circumvent such blocking by any means.

Sei Interface
Sei Interface provides a web or mobile-based means of access to the Sei Network and allows users to view balances, staking information, and initiate transaction signing requests through their connected wallets.

The Sei Interface is distinct from the Sei Network and is one, but not the exclusive, means of accessing the Sei Network. The Sei Network comprises open-source or source-available self-executing smart contracts that are deployed on the Sei blockchain. The Foundation does not control, operate, or maintain the Sei Network, and makes no representations or warranties regarding the operation, security, or availability of the Sei Network. You acknowledge and accept all risks associated with using the Sei Network, including but not limited to network downtime, protocol changes, and technical failures. By using the Sei Interface, you understand that you are not buying or selling digital assets from us and that we do not operate any staking pools on the Sei Network or control transaction execution on the Sei Network.

When using the Sei Interface to send transactions or stake tokens, you are merely inputting transaction details which are then forwarded to your connected wallet for review and signature. The Foundation does not sign transactions on your behalf, have access to your private keys, or control the execution of any transaction. All transactions must be explicitly approved and signed by you through your wallet, and are then broadcast to the Sei Network where they are processed by validators, not by the Foundation. When initiating transactions (including token transfers) through the Sei Interface, you acknowledge that you will be conducting transfers through your connected wallet, which is a third-party service not owned or operated by Aster Foundation, and you agree that (i) the Foundation does not control, audit, or assume responsibility for any transactions, risks, fees, or potential losses incurred during transfers; (ii) your wallet's security, functionality, and transaction processing are managed entirely by the third-party wallet provider; and (iii) transfers are subject to your wallet provider's terms, conditions, and security measures.

To access the Sei Interface, you must use a non-custodial wallet software, which allows you to interact with public blockchains. Your relationship with that non-custodial wallet provider is governed by the applicable terms of service (with respect to the Wallet Services, this Agreement, and with respect to a third party wallet, the applicable terms of service of such third party). We do not have custody or control over the contents of your wallet and have no ability to retrieve or transfer its contents. By connecting your wallet to our Sei Interface, you agree to be bound by this Agreement and all of the terms incorporated herein by reference.

Explore Page
The Services include an explore page that showcases applications and protocols built on the Sei Network. The explore page displays various applications, categorizes them, and may highlight trending or featured projects. When you click on applications or protocols listed on the explore page, you may be redirected to third-party websites, applications, or services that are not owned, operated, or controlled by the Foundation.

The Foundation does not endorse, recommend, or make any representations or warranties regarding any applications, protocols, or content featured on the explore page. All applications and protocols listed are developed and operated by independent third parties, and the Foundation has no affiliation with, control over, or responsibility for such applications, protocols, or their developers. You acknowledge and agree that:

a) Your use of any application or protocol accessed through the explore page is entirely at your own risk;
b) You are solely responsible for conducting your own research and due diligence before using any such applications or protocols;
c) The Foundation makes no representations regarding the security, functionality, legality, or reliability of any third-party applications or protocols;
d) The Foundation is not responsible for any losses, damages, or issues arising from your use of third-party applications or protocols; and
e) Your use of third-party applications and protocols is subject to their respective terms of service and privacy policies.
Wallet Services
The Wallet Services are non-custodial, meaning we do not store, control, or have access to your private keys, recovery phrases, or digital assets. The Wallet Services utilize technology provided by Dynamic Labs, Inc. ("Dynamic") but are hosted and operated by us.

When using the Wallet Services:

a) You will maintain full control and custody of your private keys and digital assets. Neither we nor any third-party service providers, including Dynamic, have access to or control over your private keys or digital assets.
b) Your wallet may be seamlessly accessible across multiple applications that have integrated the relevant SDK, allowing you to use the same wallet credentials across the Sei ecosystem.
c) We do not have the ability to initiate transactions on your behalf, recover your private keys, or access your funds.
d) You acknowledge the inherent risks of using blockchain technology, including but not limited to:
Volatile cryptocurrency prices and potential loss of value
Irreversible transactions once confirmed on the blockchain
Potential theft or loss of private keys resulting in permanent loss of assets
Software bugs, security vulnerabilities, or technical failures
Changes to blockchain protocols or consensus mechanisms
You are solely responsible for:

Securing and backing up your private keys and recovery phrases
Verifying all transaction details before signing
Ensuring you have sufficient funds for transactions, including network fees
Understanding the implications of any transaction you initiate
Copyright and License to You
Information Ownership. Unless otherwise indicated in writing by us, the Services and all content and other materials contained therein, including, without limitation, our logo and all designs, text, graphics, trademarks, pictures, information, data, software, sound files, and/or other files related thereto and/or associated therewith and the selection and arrangement thereof (collectively, "Content") are and shall remain the sole and proprietary property of the Foundation (including all subsidiaries and related entities) or our affiliates or licensors, if and as applicable. You represent and warrant that you own all rights, titles and interest (including copyrights and rights of publicity) in and to any Content you make available on or through the Services ("Your Content").

Any questions, comments, suggestions, ideas, feedback, reviews, or other information about the Services ("Submissions"), provided by you to Aster Foundation are non-confidential and you hereby irrevocably assign to Aster Foundation all right, title, and interest (including all intellectual property rights) in and to such Submissions. Aster Foundation will be entitled to the unrestricted use and dissemination of these Submissions for any purpose, commercial or otherwise, without acknowledgment, attribution, or compensation to you.

You acknowledge and agree that Aster Foundation may preserve Your Content and may also disclose Your Content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (i) comply with legal process, applicable laws, or government requests; (ii) enforce these Terms of Service (including our Privacy Policy); (iii) respond to claims that any content violates the rights of third parties; or (iv) protect the rights, property, or personal safety of Aster Foundation, its users, or the public. You understand that the technical processing and transmission of the Service, including Your Content, may involve transmissions over various networks and/or changes to conform and adapt to technical requirements of connecting networks or devices.

Third Party Intellectual Property. Notwithstanding anything to the contrary in these Terms, the Services and Content may include software components provided by the Foundation or its affiliates or a third party that are subject to separate license terms, in which case those license terms will govern the usage of such software components, as applicable.

Third Party Services. The Services may contain links to third-party websites ("Third-Party Websites") and/or applications ("Third-Party Applications"). When you click on a link to a Third-Party Website or Third-Party Application, we will not warn you that you have left the Services and are subject to the terms and conditions (including privacy policies, if and as applicable) of another website or destination. The Foundation provides these Third-Party Websites and Third-Party Applications only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Websites or Third-Party Applications or their products or services. You use all links in Third-Party Websites and Third-Party Applications at your own risk. Third-Party Applications may include applications, services, protocols or digital assets based on or employing the SEI Network, including such applications, services, protocols or digital assets developed with support from the Foundation. Nonetheless, the foregoing terms apply to all such applications, services, protocols or digital assets.

Limited License to You. These Terms grant users a limited and non-exclusive right to use the Services, including all Content thereon. Except as indicated otherwise herein or in any additional terms or conditions, you may not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, transmit, or otherwise exploit any of the Content on our Services, except as follows:

Your device may temporarily store copies of such materials in RAM incidental to your accessing and viewing those materials.
You may store files that are automatically cached by your web browser for display enhancement purposes.
You may download a single copy of the mobile application to your computer or mobile device solely for your own personal, non-commercial use, provided you agree to be bound by our end user license agreement for such applications.
If we provide any so-called "social media" features as part of the Services, you may take such actions as are enabled by such features and are consistent with these Terms.
You must not:

Modify copies of any Content from the Services.
Use any illustrations, photographs, video, or audio sequences or any graphics available through the Services separately from the accompanying text.
Delete or alter any copyright, trademark, or other proprietary rights notices from copies of materials available through the Services.
If you wish to make any use of Content other than that set out in this Section, please address your request to foundation@seifdn.org.

Access to Services and Assumption of Risk: You understand and acknowledge that the Services are being offered as a developmental and testing platform and are made available on an "AS IS" and "AS AVAILABLE" basis and subject to the Limitation of Liability terms below. The Services may contain errors, bugs, or inaccuracies that could cause failures, corruption, or loss of data from your devices and peripheral (including servers and computers) connected to your devices. The Foundation is not obligated to continue to develop the Services or provide any maintenance, technical, or other support for the Services. YOU ASSUME ALL RISKS AND ALL COSTS ASSOCIATED WITH OR ARISING IN ANY WAY FROM YOUR USE OF THE SERVICES, INCLUDING ANY INTERNET ACCESS FEES, BACK-UP AND RECOVERY EXPENSES, COSTS INCURRED FOR THE USE OF YOUR DEVICE AND PERIPHERALS, AND ANY DAMAGE OR LOSS TO ANY DATA, INFORMATION, EQUIPMENT, OR SOFTWARE.

Indemnification
To the maximum extent permitted by applicable law, you agree to indemnify, defend, and hold harmless the Foundation, and our respective past, present, and future employees, officers, directors, contractors, consultants, equity holders, suppliers, vendors, service providers, parent companies, subsidiaries, affiliates, agents, representatives, predecessors, successors, and assigns (individually and collectively, the "Foundation Parties"), from and against all actual or alleged claims, damages, awards, judgments, losses, liabilities of every kind, and nature whatsoever, whether known or unknown, that are caused by, arise out of, or are related to (a) your use or misuse of the Services, (b) your violation of these Terms, and/or (c) your violation of any right(s) of any third party. You agree to promptly notify the Foundation of any Claim(s) and shall cooperate fully with the Foundation Parties in defending such Claims. You further agree that the Foundation Parties shall have control of the defense or settlement of any third party Claims. THIS INDEMNITY IS IN ADDITION TO, AND NOT IN LIEU OF, ANY OTHER INDEMNITIES SET FORTH IN ANY WRITTEN AGREEMENT(S) BETWEEN YOU AND THE FOUNDATION.

Limitation of Liability
EXCEPT AS EXPRESSLY PROVIDED TO THE CONTRARY IN A WRITING BY THE FOUNDATION, THE SERVICES AND ANY CONTENT CONTAINED THEREIN ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. THE FOUNDATION (AND ITS AFFILIATE(S), LICENSOR(S) AND/OR OTHER BUSINESS ASSOCIATE(S)) MAKES NO WARRANTY THAT THE SERVICES: (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (C) WILL BE ACCURATE, RELIABLE, COMPLETE, LEGAL OR SAFE. THE FOUNDATION DISCLAIMS ALL OTHER WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT AS TO THE SERVICES, CONTENT CONTAINED THEREIN. YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND DEALING ONLINE OVER THE INTERNET AND WILL NOT HOLD US RESPONSIBLE FOR ANY BREACH OF SECURITY UNLESS IT IS DUE TO OUR GROSS NEGLIGENCE.

YOU AGREE AND ACKNOWLEDGE THAT THE FOUNDATION HAS NO CONTROL OVER AND MAKES NO GUARANTEES OR PROMISES WITH RESPECT TO THE ACCURACY OF BLOCKCHAIN DATA, DIGITAL OWNERSHIP RECORDS, OR SMART CONTRACTS. THE FOUNDATION MAKES NO OFFER OR INVITATION TO ACQUIRE, PURCHASE, TRANSFER, SELL, OR OTHERWISE DEAL IN TOKENS. TO THE EXTENT PERMITTED BY APPLICABLE LAW, YOU WAIVE ANY AND ALL RIGHTS AND CLAIMS YOU MAY HAVE, WHETHER KNOWN OR UNKNOWN AGAINST THE FOUNDATION (AND ANY RELATED PARTIES) RELATED TO THE SERVICES.

YOU REPRESENT AND WARRANT THAT YOU UNDERSTAND THE INHERENT RISKS ASSOCIATED WITH USING CRYPTOGRAPHIC AND BLOCKCHAIN-BASED SYSTEMS, AND THAT YOU HAVE A WORKING KNOWLEDGE OF THE USAGE AND INTRICACIES OF DIGITAL ASSETS, SUCH AS THOSE FOLLOWING THE ETHEREUM TOKEN STANDARD (ERC-20) AND BRIDGING ACROSS DIFFERENT BLOCKCHAIN SOLUTIONS. YOU FURTHER UNDERSTAND THAT THE MARKETS FOR THESE DIGITAL ASSETS ARE HIGHLY VOLATILE DUE TO VARIOUS FACTORS, INCLUDING ADOPTION, SPECULATION, TECHNOLOGY, SECURITY, AND REGULATION. YOU ACKNOWLEDGE AND ACCEPT THAT THE COST AND SPEED OF TRANSACTING WITH CRYPTOGRAPHIC AND BLOCKCHAIN-BASED SYSTEMS SUCH AS SEI NETWORK ARE VARIABLE AND MAY INCREASE DRAMATICALLY AT ANY TIME. YOU FURTHER ACKNOWLEDGE AND ACCEPT THE RISK THAT YOUR DIGITAL ASSETS MAY LOSE SOME OR ALL OF THEIR VALUE WHILE THEY ARE SUPPLIED TO THE PROTOCOL THROUGH THE INTERFACE. YOU UNDERSTAND THAT ANYONE CAN CREATE A TOKEN, INCLUDING FAKE VERSIONS OF EXISTING TOKENS AND TOKENS THAT FALSELY CLAIM TO REPRESENT PROJECTS, AND ACKNOWLEDGE AND ACCEPT THE RISK THAT YOU MAY MISTAKENLY TRADE THOSE OR OTHER TOKENS. YOU FURTHER ACKNOWLEDGE THAT WE ARE NOT RESPONSIBLE FOR ANY OF THESE VARIABLES OR RISKS, AND CANNOT BE HELD LIABLE FOR ANY RESULTING LOSSES THAT YOU EXPERIENCE WHILE ACCESSING OR USING THE SERVICE. ACCORDINGLY, YOU UNDERSTAND AND AGREE TO ASSUME FULL RESPONSIBILITY FOR ALL OF THE RISKS OF ACCESSING AND USING THE SERVICE, INCLUDING THE INTERFACE TO INTERACT WITH THE PROTOCOL.

TO THE FULLEST EXTENT PROVIDED BY LAW, IN NO EVENT WILL THE FOUNDATION OR ITS AFFILIATES, OR ITS OR THEIR LICENSORS, SERVICE PROVIDERS, EMPLOYEES, CONTRACTORS, AGENTS, OFFICERS, OR DIRECTORS, BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, LOSS OF DIGITAL ASSETS, LOSS OF PRIVATE KEY, LOSS OF SEED PHRASE, LOSS OF ACCESS TO ANY DIGITAL WALLET, OR ANY OTHER DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE SERVICES, INCLUDING BUT NOT LIMITED TO ANY CONTENT ON THE SERVICES OR ANY OTHER WEBSITES AND MOBILE APPLICATIONS OR ANY ITEMS OBTAINED THROUGH THE SERVICES OR SUCH OTHER WEBSITES AND MOBILE APPLICATIONS, WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE.

IF ANY PART OF THESE WARRANTY DISCLAIMERS OR LIMITATIONS OF LIABILITY IS FOUND TO BE INVALID OR UNENFORCEABLE FOR ANY REASON OR IF WE ARE OTHERWISE FOUND TO BE LIABLE TO YOU IN ANY MANNER, THEN OUR AGGREGATE LIABILITY FOR ALL CLAIMS UNDER SUCH CIRCUMSTANCES FOR LIABILITIES SHALL NOT EXCEED ONE HUNDRED U.S. DOLLARS ($100.00 USD).

ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICES MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES, OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM SHALL BE DEEMED PERMANENTLY WAIVED AND BARRED.

THIS SECTION DOES NOT AFFECT ANY LIABILITY THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH JURISDICTIONS THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU. IN SUCH JURISDICTIONS, OUR LIABILITY IS LIMITED TO THE EXTENT PERMITTED BY LAW, THEREBY MINIMIZING OUR LIABILITY TO YOU TO THE LOWEST AMOUNT PERMITTED BY APPLICABLE LAW.

NO ACTIVITY OR INTERACTION WITH THE SERVICES CONSTITUTES A SALE OF VIRTUAL ASSETS TO THE PUBLIC, AND THE SERVICES ARE NOT INTENDED TO CONSTITUTE A SECURITIES OFFERING OR INVESTMENT PRODUCT. IF YOU DO NOT UNDERSTAND THIS TO BE THE CASE, PLEASE CEASE USE OF THE SERVICES AND REFRAIN FROM ANY FURTHER INTERACTION WITH THE SERVICES.

Dispute Resolution
This Section includes an arbitration agreement and an agreement that all claims will be brought only in an individual capacity (and not as a class action or other representative proceeding). Please read it carefully.

Informal Process. You agree that in the event of any dispute between you and the Foundation, you will first contact the Foundation in writing and make a good faith sustained effort for no less than forty-five (45) days to resolve the dispute before resorting to more formal means of resolution, including without limitation any court action.

Agreement to Arbitrate. Any dispute, controversy, or claim that remains unresolved after the forty-five (45) day informal dispute resolution process concludes (collectively, "Dispute") relating in any way to these Terms or the Foundation's services and/or products, including but not limited to the Services, or relating in any way to the communications between you and the Foundation or any other user of the Services, will be finally resolved by binding arbitration. This mandatory arbitration agreement applies to both you and the Foundation. However, this arbitration agreement does not (a) govern any Dispute by the Foundation for infringement of its intellectual property or access to the Services that is unauthorized or exceeds authorization granted in these Terms, or (b) bar you from making use of applicable small claims court procedures in appropriate cases within the Cayman Islands.

Arbitration Procedure and Rules. Any Dispute, including all questions of arbitrability, shall be settled by arbitration administered by the Cayman International Arbitration Centre (CIAC) in accordance with its International Arbitration Rules by a sole arbitrator. The parties hereto shall endeavor to agree upon the arbitrator, and if they fail to do so within twenty-one (21) days of the commencement of the arbitration, the appointment shall be made by the Cayman Islands Arbitration Centre in accordance with its Arbitration Rules. The place, or legal seat of arbitration, shall be the Cayman Islands, and the language of the arbitration shall be English.

You may only bring claims in your individual capacity on your own behalf, and not in any representative capacity or on behalf of any class or purported class, and no arbitration you commence hereunder may be joined with or include any claims by any other persons without the consent of both parties. Each party shall be exclusively responsible for paying its own arbitration filing fees, which may later be allocated by the arbitrator as set forth below.

Subject to the limitation of liability set forth above, the arbitrator shall have the power to grant any interim or provisional measures that the arbitrator deems appropriate, including, but not limited to, injunctive relief and specific performance, and any interim or provisional measures ordered by the arbitrator may be specifically enforced by any court of competent jurisdiction as a final award. Nothing herein, however, shall authorize the arbitrator to act as amiable compositeurs, to proceed ex aequo et bono, or to exercise rights of iura novit curia. Each party hereto retains the right to seek interim measures from a judicial authority, and any such request shall not be deemed incompatible with the agreement to arbitrate or a waiver of the right to arbitrate. The arbitrator shall award the prevailing party, if any is determined by the arbitrator, its reasonable costs, including reasonable attorney's fees. Judgment on any award rendered by the arbitrator may be entered in any court of competent jurisdiction. No information concerning an arbitration, beyond the names of the parties, their counsel, or the relief requested, may be unilaterally disclosed to a third party by any party unless required by law. Any documentary or other evidence given by any party or witness in any arbitration shall be treated as confidential by any party whose access to such evidence arises exclusively because of its participation in the arbitration and shall not be disclosed to any third party (other than a witness or expert), except as may be required by law. Any party who commences any judicial proceeding in connection with an arbitration initiated hereunder shall endeavor to have the judicial record of any such proceeding sealed to the extent permitted by law.

YOU AGREE THAT ANY CLAIM YOU MAY HAVE ARISING OUT OF OR RELATED TO YOUR RELATIONSHIP WITH THE FOUNDATION MUST BE BROUGHT WITHIN ONE (1) YEAR AFTER SUCH CLAIM AROSE; OTHERWISE, YOUR CLAIM WILL BE PERMANENTLY BARRED.

Miscellaneous
Governing Law and Venue. Any dispute arising from these Terms and your use of the Service will be governed by and construed and enforced in accordance with the laws of the Cayman Islands, without regard to their conflicts of laws provisions, without regard to choice of law principles, and the parties hereby expressly exclude the application of the UN Convention on the International Sale of Goods hereto. The parties hereby submit to the exclusive jurisdiction of the Grand Court of the Cayman Islands, in any litigation arising out of the Agreement. The parties agree that they will not assert any claim that (i) they are not subject to the jurisdiction of such courts, (ii) the venue is improper, (iii) the forum is inconvenient, or (iv) any similar objection, claim or argument.

Severability. If any term, clause or provision of these Terms is held invalid or unenforceable, then that term, clause, or provision will be severable from these Terms and will not affect the validity or enforceability of any remaining part of that term, clause, or provision, or any other term, clause, or provision of these Terms.

Waiver. If we fail to insist that you perform any of your obligations under these Terms, or if we do not enforce our rights against you, or if we delay in doing so, that will not mean that we have waived our rights against you and will not mean that you do not have to comply with those obligations. If we do waive a default by you or choose to waive any of these Terms, we will only do so expressly and in writing, and that will not mean that we will automatically waive any later default by you.

Assignability. These Terms are personal to you, and are not assignable, transferable, or sublicensable by you except with the Foundation's prior written consent.

Notices. All notices under these Terms will be in writing and will be deemed to have been duly given when received, if personally delivered or sent by certified or registered mail, return receipt requested; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; or the day after it is sent, if sent for next day delivery by recognized overnight delivery service.

Entire Agreement. These Terms (together with those incorporated by reference herein) constitute the entire agreement between you and Aster Foundation governing your access to and use of the Services. These Terms supersede any prior agreements between you and Aster Foundation with respect to the Services, whether written or oral, and no modification of these Terms shall be effective unless made in writing and expressly agreed to by an authorized representative of Aster Foundation.

Contact us
If you have any questions about our Services or these Terms or need to report a violation of these terms, please email us at foundation@seifdn.org.`